# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47eea80679b0a445604314c5566f13ae9fc7fa4f38c594e9dce830c7cc4f5d445d4ffde1a13cd757fa300013452b7c2de29e22001743f7d5d1e01de4b4543123

test:
  secret_key_base: 134ebcda78875a65b13723d0ff7d09eeec0ab127c891ff867438c106c12c7738ea4aac488c41201e2e9b9cb8f3a7a94a7599dd3912d42e035ea4b78e461ae901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
